In [ ]:
from sklearn.cluster import KMeans
import numpy as np

In [ ]:
X = np.array([[1, 2], [1, 3], [1, 4], [1, 21], [10, 41], [10, 10]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [ ]:
kmeans.labels_

array([1, 1, 1, 1, 0, 1], dtype=int32)

In [ ]:
kmeans.predict([[1,1],[2,2]])

array([1, 1], dtype=int32)

In [ ]:
kmeans.cluster_centers_

array([[10. , 41. ],
       [ 2.8,  8. ]])