In [44]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [8]:
iris=load_iris()

In [12]:
iris.data[5]

array([5.4, 3.9, 1.7, 0.4])

In [13]:
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [16]:
iris.data[::5]

array([[5.1, 3.5, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.4, 1.7, 0.2],
       [5. , 3. , 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.8, 3. , 1.4, 0.3],
       [7. , 3.2, 4.7, 1.4],
       [5.7, 2.8, 4.5, 1.3],
       [5. , 2. , 3.5, 1. ],
       [6.7, 3.1, 4.4, 1.4],
       [5.9, 3.2, 4.8, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [5.5, 2.4, 3.8, 1.1],
       [6. , 3.4, 4.5, 1.6],
       [5.5, 2.6, 4.4, 1.2],
       [5.7, 3. , 4.2, 1.2],
       [6.3, 3.3, 6. , 2.5],
       [7.6, 3. , 6.6, 2.1],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 3.2, 5.3, 2.3],
       [6.9, 3.2, 5.7, 2.3],
       [7.2, 3.2, 6. , 1.8],
       [7.4, 2.8, 6.1, 1.9],
       [7.7, 3. , 6.1, 2.3],
       [6.7, 3.1, 5.6, 2.4],
       [6.7, 3. , 5.2, 2.3]])

In [17]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [18]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [22]:
type(iris.data)

numpy.ndarray

In [23]:
type(iris.target)

numpy.ndarray

In [26]:
iris.data.shape

(150, 4)

In [28]:
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.5,random_state=40)

In [30]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((75, 4), (75, 4), (75,), (75,))

In [34]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [36]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
knn.score(X_train,y_train),knn.score(X_test,y_test)

(0.9733333333333334, 0.9333333333333333)

In [38]:
confusion_matrix(y_test,y_pred)

array([[27,  0,  0],
       [ 0, 22,  0],
       [ 0,  5, 21]])

In [39]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        27\n           1       0.81      1.00      0.90        22\n           2       1.00      0.81      0.89        26\n\n    accuracy                           0.93        75\n   macro avg       0.94      0.94      0.93        75\nweighted avg       0.95      0.93      0.93        75\n'

In [42]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        27
           1       0.81      1.00      0.90        22
           2       1.00      0.81      0.89        26

    accuracy                           0.93        75
   macro avg       0.94      0.94      0.93        75
weighted avg       0.95      0.93      0.93        75

